export const SIGNUP_USER = "SIGNUP_USER"
export const CLEAR_AUTH_ERRORS = "CLEAR_USER_ERRORS"
export const SIGNUP_USER_ERROR = "SIGNUP_USER_ERROR"
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS"
export const LOGIN_USER = "LOGIN_USER"
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR"
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"

export const GET_TICKETS = "GET_TICKETS"
export const GET_TICKETS_SUCCESS = "GET_TICKETS_SUCCESS"
export const GET_TICKETS_ERROR = "GET_TICKETS_ERROR"
export const CLEAR_TICKET_ERRORS = "CLEAR_TICKET_ERRORS"

export const SEARCH_MOVIE = "SEARCH_MOVIE";
export const SEARCH_MOVIE_SUCCESS = "SEARCH_MOVIE_SUCCESS";
export const SEARCH_MOVIE_ERROR = "SEARCH_MOVIE_ERROR";
export const SEARCH_MOVIE_ERRORS = "SEARCH_MOVIE_ERRORS";

export const CREATE_TICKET = "CREATE_TICKET"
export const CREATE_TICKET_SUCCESS = "CREATE_TICKET_SUCCESS"
export const CREATE_TICKET_ERROR = "CREATE_TICKET_ERROR"